export const tableDataContainer = [
  {
    sn: 1,
    title: "Raw Hide Import",
    description: "Bovine hide shipment from Brazil",
    date: "2025-01-05",
    type: "container",
    amount: 2500,
    rate: 1500,
    amountNGN: 3750000,
    status: "Completed"
  },
  {
    sn: 2,
    title: "Leather Export",
    description: "Processed leather sent to Dubai",
    date: "2025-01-07",
    type: "container",
    amount: 1800,
    rate: 1520,
    amountNGN: 2736000,
    status: "Pending"
  },
  {
    sn: 3,
    title: "Cow Skin Purchase",
    description: "Local hide supply from Kano",
    date: "2025-01-10",
    type: "Purchase",
    amount: 900,
    rate: 1400,
    amountNGN: 1260000,
    status: "Completed"
  },
  {
    sn: 4,
    title: "Shipment Clearance",
    description: "Port clearance charges",
    date: "2025-01-12",
    type: "Expense",
    amount: 400,
    rate: 1500,
    amountNGN: 600000,
    status: "Approved"
  },
  {
    sn: 5,
    title: "Wele Supply",
    description: "Frozen Wele delivery to Lagos",
    date: "2025-01-14",
    type: "Sale",
    amount: 1200,
    rate: 1550,
    amountNGN: 1860000,
    status: "Completed"
  },
  {
    sn: 6,
    title: "Transport Fee",
    description: "Cargo transport to warehouse",
    date: "2025-01-17",
    type: "Expense",
    amount: 270,
    rate: 1500,
    amountNGN: 405000,
    status: "Completed"
  },
  {
    sn: 7,
    title: "Hide Processing",
    description: "Factory processing charges",
    date: "2025-01-20",
    type: "Expense",
    amount: 360,
    rate: 1500,
    amountNGN: 540000,
    status: "Pending"
  },
  {
    sn: 8,
    title: "Bulk Export",
    description: "Bulk leather goods shipment",
    date: "2025-01-22",
    type: "Export",
    amount: 3000,
    rate: 1500,
    amountNGN: 4500000,
    status: "Completed"
  },
  {
    sn: 9,
    title: "Supplier Payment",
    description: "Payment to supplier in Kenya",
    date: "2025-01-25",
    type: "Payment",
    amount: 1000,
    rate: 1525,
    amountNGN: 1525000,
    status: "Approved"
  },
  {
    sn: 10,
    title: "Cold Storage",
    description: "Cold room rental",
    date: "2025-01-27",
    type: "Expense",
    amount: 200,
    rate: 1500,
    amountNGN: 300000,
    status: "Completed"
  },
  {
    sn: 11,
    title: "Hide Import",
    description: "Shipment from Ethiopia",
    date: "2025-01-29",
    type: "Import",
    amount: 2200,
    rate: 1510,
    amountNGN: 3322000,
    status: "Pending"
  },
  {
    sn: 12,
    title: "Packaging Cost",
    description: "Export packaging materials",
    date: "2025-02-01",
    type: "Expense",
    amount: 180,
    rate: 1500,
    amountNGN: 270000,
    status: "Completed"
  },
  {
    sn: 13,
    title: "Online Order",
    description: "International buyer order",
    date: "2025-02-03",
    type: "Sale",
    amount: 1450,
    rate: 1540,
    amountNGN: 2233000,
    status: "Pending"
  },
  {
    sn: 14,
    title: "Broker Fee",
    description: "Customs broker payment",
    date: "2025-02-05",
    type: "Expense",
    amount: 120,
    rate: 1500,
    amountNGN: 180000,
    status: "Completed"
  },
  {
    sn: 15,
    title: "Wele Distribution",
    description: "Wholesale distribution to markets",
    date: "2025-02-08",
    type: "Sale",
    amount: 1600,
    rate: 1500,
    amountNGN: 2400000,
    status: "Completed"
  },
  {
    sn: 16,
    title: "Damaged Stock",
    description: "Spoilt hide stock",
    date: "2025-02-10",
    type: "Loss",
    amount: 300,
    rate: 1500,
    amountNGN: 450000,
    status: "Declined"
  },
  {
    sn: 17,
    title: "Supplier Bonus",
    description: "Performance incentive",
    date: "2025-02-12",
    type: "Expense",
    amount: 100,
    rate: 1500,
    amountNGN: 150000,
    status: "Approved"
  },
  {
    sn: 18,
    title: "International Order",
    description: "High volume leather demand",
    date: "2025-02-14",
    type: "Export",
    amount: 4000,
    rate: 1550,
    amountNGN: 6200000,
    status: "Pending"
  },
  {
    sn: 19,
    title: "Warehouse Rent",
    description: "Monthly storage fee",
    date: "2025-02-17",
    type: "Expense",
    amount: 500,
    rate: 1500,
    amountNGN: 750000,
    status: "Completed"
  },
  {
    sn: 20,
    title: "Final Delivery",
    description: "Customer final batch",
    date: "2025-02-20",
    type: "Sale",
    amount: 2100,
    rate: 1500,
    amountNGN: 3150000,
    status: "Completed"
  }
];

// --- Dropdown Options ---
export const dropdownOptions = {
    length: ["20 ft", "40 ft", "45 ft"],
    entity: ["Entity A", "Entity B", "Entity C"],
    collaborators: ["Adelola Hosea", "Dennis Scott", "Lara Williams"],
    ports: ["London, England", "Shanghai, China", "Lagos, Nigeria"],
    country: ["London, England", "USA", "Germany"],
    funding: ["Owners", "Bank Loan", "Investor"],
    supplier: ["Supply Code 1", "Supply Code 2", "Supply Code 3"],
    unitFee: ["Pieces", "Cartons", "Pallets"],
    unitPrice: ["Unit Price 1", "Unit Price 2", "Unit Price 3"],
    warehouseCharge: ["Warehouse A", "Warehouse B"],
    outgoings: ["Outgoings 1", "Outgoings 2"],
    role: ["Role A", "Role B"],
    cargoFee: ["Cargo Fee A", "Cargo Fee B"],
    load: ["Load Transportation A", "Load Transportation B"],
    offload: ["Offload and Stacking Fee A", "Offload and Stacking Fee B"],
    clearanceFee: ["Clearance Fee A", "Clearance Fee B"],
    approvedStatus: ["Approved", "Pending", "Declined"],
    type: ["Advertising", "Legal", "Maintenance"],
    rate: ["1500", "1520", "1400"],
};

// --- Initial Container Data ---
export const initialContainerData = {
    containerID: "FIL6100000",
    totalPieces: 2475,
    averageWeight: 50.82,
    netWeight: 11.8,
    maxWeight: 100,
    grossWeight: 26000,
    netValue: 25000,
    status: "Approved",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eleifend, lectus at laoreet dictum, lorem ipsum sollicitudin elit, ac tempus nibh risus id libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec dictum, velit sed laoreet dapibus, quam orci vehicula leo, ac posuere mauris odio vel mi. Integer lacinia massa vel turpis varius, ut tempor lorem euismod.",
    partner: "Partner 1",
    trackingNumber: "0582",
    length: "20 ft",
    entity: "Entity A",
    sourceLocation: "London, England",
    sourceCountry: "London, England",
    destinationPort: "London, England",
    destinationCountry: "London, England",
    funding: "Owners",
    supplier: "Supply Code 1",
    collaborators: ["Adelola Hosea", "Dennis Scott", "Lara Williams"],
    // Unit and Fee
    pieces: "Pieces",
    unitPrice: "Unit Price 1",
    warehouseCharge: "Warehouse A",
    depositAmount: "5000",
    outgoings: "Outgoings 1",
    depositAmountUSD: "2500",
    balanceAmount: "1000",
    rollBackRate: "1500",
    returnAmount: "1000",
    cargoFee: "Cargo Fee A",
    rollBackFee: "500",
    cargoFeeNGN: "500",
    clearanceFee: "Clearance Fee A",
    loadTransportation: "Load Transportation A",
    offloadAndStackingFee: "Offload and Stacking Fee A",
    originalDate: "2025-01-20", // ISO format for date input
    paymentDate: "2025-01-20",
    shipmentDate: "2025-01-20",
    tripDate: "2025-01-20",
    estimatedArrivalDate: "2025-01-20",
    approvedDate: "2025-01-20",
    otherExpenses: [
        { id: 1, description: "Asset Management", startDate: "2024-05-30", type: "Advertising", amount: 100, rate: 1500, total: 125000, approved: true },
    ]
};

export const SaleContainerData = Array.from({ length: 10 }, (_, i) => ({
  id: i + 1,
  name: `Container ${i + 1}`,
  containerID: `FIL61000${i + 1}`,
  totalPieces: 2000 + i * 100,
  averageWeight: 50 + i,
  netWeight: 10 + i,
  maxWeight: 100 + i,
  WarehouseArrivalDat:"25/02/2025" + i,
  grossWeight: 25000 + i * 100,
  netValue: 20000 + i * 100,
  status: "Approved",
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  partner: `Partner ${i + 1}`,
}));
